"""Search every fund that files 13F, by name or CIK.

Backed by filers.csv, a bundled index of ~8,800 filers (~330KB) generated by
build_filer_index.py from SEC's quarterly Form 13F data set. It is loaded into
memory once on first search and scanned directly -- at this size that costs a
couple of MB and well under a millisecond per query, so there's no index,
database or external call involved.

Fund managers file under legal entity names rather than the name they're known
by -- David Einhorn's Greenlight files as "DME Capital Management, LP", Mohnish
Pabrai's as "Dalal Street, LLC" -- which is exactly why searching beats a
hand-maintained list.
"""

import csv
import os

FILERS_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "filers.csv")

MAX_RESULTS = 25

_filers = None


def _load():
    """Read the index on first use. Returns a list of (cik, name, name_lower)."""
    global _filers
    if _filers is None:
        rows = []
        try:
            with open(FILERS_PATH, encoding="utf-8", newline="") as handle:
                for row in csv.DictReader(handle):
                    name = row["name"]
                    rows.append((row["cik"], name, name.lower()))
        except OSError:
            # A missing index disables search but leaves the rest of the page
            # working, since favourites carry their own CIKs.
            rows = []
        _filers = rows
    return _filers


def search(query, limit=MAX_RESULTS):
    """Find filers whose name contains the query, best matches first.

    A numeric query is treated as a CIK prefix instead.
    """
    query = (query or "").strip().lower()
    if len(query) < 2:
        return []

    filers = _load()

    if query.isdigit():
        return [
            {"cik": cik, "name": name}
            for cik, name, _ in filers
            if cik.startswith(query)
        ][:limit]

    matches = []
    for cik, name, name_lower in filers:
        if query not in name_lower:
            continue
        if name_lower.startswith(query):
            rank = 0
        elif any(word.startswith(query) for word in name_lower.split()):
            rank = 1
        else:
            rank = 2
        matches.append((rank, name_lower, cik, name))

    matches.sort()
    return [{"cik": cik, "name": name} for _, _, cik, name in matches[:limit]]


def count():
    """How many filers are in the index."""
    return len(_load())
